export const POST_SALES_RETURN_SUCCESS = 'POST_SALES_RETURN_SUCCESS';
export const STORE_SALES_RETURN_SUCCESS = 'STORE_SALES_RETURN_SUCCESS';
export const GET_SALES_RETURN_DATA_SUCCESS = 'GET_SALES_RETURN_DATA_SUCCESS';
export const GET_SALES_RETURN_SUCCESS = 'GET_SALES_RETURN_SUCCESS';