export const LOAD_ORDERS_WEB_SUCCESS = 'LOAD_ORDERS_WEB_SUCCESS';
export const LOAD_ORDERS_SUCCESS = 'LOAD_ORDERS_SUCCESS';
export const POST_NEW_ORDER_SUCCESS = 'POST_NEW_ORDER_SUCCESS';
export const SYNC_STATUS_SUCCESS = 'SYNC_STATUS_SUCCESS';
export const PATCH_ORDER_SUCCESS = 'PATCH_ORDER_SUCCESS';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const OFFLINE_ORDER_ADD = 'OFFLINE_ORDER_ADD';