export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const LOAD_PRICE_BOOK_DATA_SUCCESS = 'LOAD_PRICE_BOOK_DATA_SUCCESS';
export const GET_PRICE_BOOK_FROM_REALM_SUCCESS = 'GET_PRICE_BOOK_FROM_REALM_SUCCESS';
export const LOAD_EXPENSE_TYPE_SUCCESS = 'LOAD_EXPENSE_TYPE_SUCCESS';