# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'anna_app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for anna_app

  target 'anna_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing


    pod 'react-native-maps', :path => '../node_modules/react-native-maps'



    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'



    pod 'react-native-config', :path => '../node_modules/react-native-config'

    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'



    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  end

  target 'anna_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'anna_app-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for anna_app-tvOS

  target 'anna_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
