export const LOAD_ALL_WEB_PRODUCTS_SUCCESS = 'LOAD_ALL_WEB_PRODUCTS_SUCCESS';
export const LOAD_ALL_WEB_RETURN_PRODUCTS_SUCCESS = 'LOAD_ALL_WEB_RETURN_PRODUCTS_SUCCESS';
export const POST_STOCK_CONFIRMATION_SUCCESS = 'POST_STOCK_CONFIRMATION_SUCCESS';